# Generated by Django 4.2.10 on 2025-03-22 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(verbose_name='使用目的')),
                ('destination', models.CharField(max_length=100, verbose_name='目的地')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='开始日期')),
                ('planned_return_date', models.DateField(verbose_name='计划归还日期')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='实际归还日期')),
                ('start_mileage', models.PositiveIntegerField(default=0, verbose_name='起始里程')),
                ('end_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='结束里程')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_usages', to=settings.AUTH_USER_MODEL, verbose_name='使用人')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='vehicle.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '车辆使用记录',
                'verbose_name_plural': '车辆使用记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
