# Generated by Django 4.2.10 on 2025-03-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='status',
        ),
    ]
