# Generated by Django 4.2.10 on 2025-03-22 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200, verbose_name='用途')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('start_location', models.CharField(max_length=200, verbose_name='出发地点')),
                ('destination', models.CharField(max_length=200, verbose_name='目的地')),
                ('passengers', models.PositiveSmallIntegerField(default=1, verbose_name='乘客数量')),
                ('passenger_details', models.TextField(blank=True, null=True, verbose_name='乘客详情')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=10, verbose_name='优先级')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='vehicle.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '车辆预约',
                'verbose_name_plural': '车辆预约',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('start_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='起始里程')),
                ('end_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='结束里程')),
                ('fuel_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='耗油量(L)')),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='油费(元)')),
                ('toll_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='通行费(元)')),
                ('parking_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='停车费(元)')),
                ('other_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='其他费用(元)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_record', to='reservation.reservation', verbose_name='预约')),
            ],
            options={
                'verbose_name': '行程记录',
                'verbose_name_plural': '行程记录',
            },
        ),
        migrations.CreateModel(
            name='ReservationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reservation_attachments/', verbose_name='文件')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reservation.reservation', verbose_name='预约')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reservation_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '预约附件',
                'verbose_name_plural': '预约附件',
            },
        ),
    ]
